/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopoly;

import static monopoly.Monopoly.players;
import static monopoly.Monopoly.turn;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author r.pablo
 */
public class Board extends javax.swing.JFrame {

    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
        this.setVisible(true);
        this.setSize(1745, 2000);// change the size
        btnHouse.setEnabled(false);
        btnSell.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPicture = new javax.swing.JLabel();
        lblTurn = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnHouse = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();
        lblNumber = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnEnd = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        lblPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/s-l300.jpg"))); // NOI18N
        lblPicture.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblPicture);
        lblPicture.setBounds(0, 0, 1024, 1020);

        lblTurn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(lblTurn);
        lblTurn.setBounds(1410, 0, 100, 20);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(1030, 910, 80, 30);

        btnHouse.setText("House");
        getContentPane().add(btnHouse);
        btnHouse.setBounds(1030, 840, 90, 30);

        btnSell.setText("Sell");
        getContentPane().add(btnSell);
        btnSell.setBounds(1030, 880, 90, 23);

        lblNumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(lblNumber);
        lblNumber.setBounds(1090, 10, 30, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/deeds.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1020, 50, 730, 760);

        btnEnd.setText("Start");
        btnEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnd);
        btnEnd.setBounds(1030, 810, 90, 23);
        getContentPane().add(lblMessage);
        lblMessage.setBounds(1410, 20, 100, 14);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/Money1.png"))); // NOI18N
        lblBackground.setText("sa");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(-30, 0, 1790, 1060);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1230, 900, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Thanks for playing", "Monpoly", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);

    }//GEN-LAST:event_btnExitActionPerformed

    private void btnEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndActionPerformed
         btnEnd.setText("End turn");
          btnHouse.setEnabled(true);
        btnSell.setEnabled(true);
        turn++;
        updateLabels();
        players[turn].takeTurn();
        updateLabels();
        System.out.println(turn);
        if (turn == players.length - 1) {
            turn = -1;
        }
        System.out.println("turn end");
    }//GEN-LAST:event_btnEndActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnd;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHouse;
    private javax.swing.JButton btnSell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblTurn;
    // End of variables declaration//GEN-END:variables

    private void updateLabels() {
        lblMessage.setText("$" + Integer.toString(players[turn].cash));
        lblTurn.setText(players[turn].name + "'s turn");
    }
}
