/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopoly;

import static monopoly.Monopoly.players;
import static monopoly.Monopoly.turn;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author r.pablo
 */
public class Board extends javax.swing.JFrame {

    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
        this.setVisible(true);
        this.setSize(1785, 2000);// change the size

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPicture = new javax.swing.JLabel();
        lblDisplay = new javax.swing.JLabel();
        lblDisplay2 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnHouse = new javax.swing.JButton();
        btnMoney = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();
        lblNumber = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnEnd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        lblPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPicture.setIcon(new javax.swing.ImageIcon("C:\\Users\\r.pablo\\Desktop\\s-l300.jpg")); // NOI18N
        lblPicture.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblPicture);
        lblPicture.setBounds(10, 0, 1024, 1020);

        lblDisplay.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisplay.setText("Player");
        lblDisplay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblDisplay);
        lblDisplay.setBounds(1040, 0, 50, 40);

        lblDisplay2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDisplay2.setText("turn");
        getContentPane().add(lblDisplay2);
        lblDisplay2.setBounds(1110, 10, 40, 20);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(1040, 970, 80, 30);

        btnHouse.setText("Buy houses/ Sell house");
        getContentPane().add(btnHouse);
        btnHouse.setBounds(1040, 870, 190, 30);

        btnMoney.setText("Check Money");
        getContentPane().add(btnMoney);
        btnMoney.setBounds(1040, 940, 150, 23);

        btnSell.setText("Mortage");
        getContentPane().add(btnSell);
        btnSell.setBounds(1040, 910, 90, 23);

        lblNumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(lblNumber);
        lblNumber.setBounds(1090, 10, 30, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\r.pablo\\Desktop\\deeds.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1040, 30, 730, 760);

        btnEnd.setText("End Turn");
        getContentPane().add(btnEnd);
        btnEnd.setBounds(1040, 840, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Thanks for playing", "Monpoly", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);

    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnd;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHouse;
    private javax.swing.JButton btnMoney;
    private javax.swing.JButton btnSell;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JLabel lblDisplay2;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblPicture;
    // End of variables declaration//GEN-END:variables
}
