package monopoly;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import static monopoly.Monopoly.players;
import static monopoly.Monopoly.turn;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 * @author r.pablo
 */
public class Board extends javax.swing.JFrame {
    // array
    public static JLabel[] dice;
    
    private Timer musicCheck; 

    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
        this.setVisible(true);
        this.setSize(1745, 2000);// change the size
        btnHouse.setEnabled(false); // set the button to be disenable so it
        // can't be used at the start
        btnSell.setEnabled(false); // set the button to be disenable so it
        // can't be used at the start
        JLabel[] dice = {
            lblDice1, lblDice2, lblDice3, lblDice4,  lblDice5,  lblDice6, 
            lblDice7, lblDice8, lblDice9, lblDice10, lblDice11, lblDice12 
        }; 
        this.dice = dice; 
        // set the every lbl dice invisible 
        for (JLabel die : dice) {
            die.setVisible(false);
        }
        MediaPlayer media = new MediaPlayer();
        media.playWAV("Monopoly Deluxe - Music 1.wav");
        musicCheck = new Timer(1, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (media.isRunning() == false) {
                    media.playWAV("Monopoly Deluxe - Music 1.wav"); 
                }
            }
        }); 
        musicCheck.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTurn = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnHouse = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();
        lblNumber = new javax.swing.JLabel();
        lblDeeds = new javax.swing.JLabel();
        btnEnd = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        lblP1 = new javax.swing.JLabel();
        lblP2 = new javax.swing.JLabel();
        lblP3 = new javax.swing.JLabel();
        lblP4 = new javax.swing.JLabel();
        lblP5 = new javax.swing.JLabel();
        lblP6 = new javax.swing.JLabel();
        lblP7 = new javax.swing.JLabel();
        lblP8 = new javax.swing.JLabel();
        lblDice1 = new javax.swing.JLabel();
        lblDice2 = new javax.swing.JLabel();
        lblDice3 = new javax.swing.JLabel();
        lblDice4 = new javax.swing.JLabel();
        lblDice5 = new javax.swing.JLabel();
        lblDice6 = new javax.swing.JLabel();
        lblDice7 = new javax.swing.JLabel();
        lblDice8 = new javax.swing.JLabel();
        lblDice9 = new javax.swing.JLabel();
        lblDice10 = new javax.swing.JLabel();
        lblDice11 = new javax.swing.JLabel();
        lblDice12 = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        lblTurn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(lblTurn);
        lblTurn.setBounds(1410, 0, 100, 20);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(1030, 910, 80, 30);

        btnHouse.setText("House");
        getContentPane().add(btnHouse);
        btnHouse.setBounds(1030, 840, 90, 30);

        btnSell.setText("Sell");
        getContentPane().add(btnSell);
        btnSell.setBounds(1030, 880, 90, 23);

        lblNumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(lblNumber);
        lblNumber.setBounds(1090, 10, 30, 20);

        lblDeeds.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/deeds.jpg"))); // NOI18N
        lblDeeds.setText("jLabel10");
        getContentPane().add(lblDeeds);
        lblDeeds.setBounds(1020, 50, 730, 760);

        btnEnd.setText("Start");
        btnEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnd);
        btnEnd.setBounds(1030, 810, 90, 23);
        getContentPane().add(lblMessage);
        lblMessage.setBounds(1410, 20, 100, 14);

        lblP1.setText("jLabel1");
        getContentPane().add(lblP1);
        lblP1.setBounds(930, 980, 34, 20);

        lblP2.setText("jLabel3");
        getContentPane().add(lblP2);
        lblP2.setBounds(930, 910, 34, 14);

        lblP3.setText("jLabel2");
        getContentPane().add(lblP3);
        lblP3.setBounds(930, 930, 34, 14);

        lblP4.setText("jLabel3");
        getContentPane().add(lblP4);
        lblP4.setBounds(930, 950, 34, 14);

        lblP5.setText("jLabel3");
        getContentPane().add(lblP5);
        lblP5.setBounds(970, 910, 34, 14);

        lblP6.setText("jLabel3");
        getContentPane().add(lblP6);
        lblP6.setBounds(990, 920, 34, 14);

        lblP7.setText("jLabel3");
        getContentPane().add(lblP7);
        lblP7.setBounds(980, 950, 34, 20);

        lblP8.setText("jLabel3");
        getContentPane().add(lblP8);
        lblP8.setBounds(980, 980, 34, 14);

        lblDice1.setIcon(new javax.swing.ImageIcon("C:\\Users\\r.pablo\\Desktop\\Will and Raden FInal Project For Computer Science 30S\\Pictures\\dice1.png")); // NOI18N
        getContentPane().add(lblDice1);
        lblDice1.setBounds(120, 140, 110, 130);

        lblDice2.setIcon(new javax.swing.ImageIcon("C:\\Users\\r.pablo\\Desktop\\Will and Raden FInal Project For Computer Science 30S\\Pictures\\dice2.png")); // NOI18N
        lblDice2.setText("jLabel1");
        getContentPane().add(lblDice2);
        lblDice2.setBounds(130, 230, 120, 160);

        lblDice3.setIcon(new javax.swing.ImageIcon("C:\\Users\\r.pablo\\Desktop\\Will and Raden FInal Project For Computer Science 30S\\Pictures\\dice3.png")); // NOI18N
        lblDice3.setText("jLabel1");
        getContentPane().add(lblDice3);
        lblDice3.setBounds(130, 340, 120, 150);

        lblDice4.setIcon(new javax.swing.ImageIcon("C:\\Users\\r.pablo\\Desktop\\Will and Raden FInal Project For Computer Science 30S\\Pictures\\dice4.png")); // NOI18N
        lblDice4.setText("jLabel1");
        getContentPane().add(lblDice4);
        lblDice4.setBounds(120, 450, 120, 130);

        lblDice5.setIcon(new javax.swing.ImageIcon("C:\\Users\\r.pablo\\Desktop\\Will and Raden FInal Project For Computer Science 30S\\Pictures\\dice5.png")); // NOI18N
        lblDice5.setText("jLabel1");
        getContentPane().add(lblDice5);
        lblDice5.setBounds(120, 520, 120, 180);

        lblDice6.setIcon(new javax.swing.ImageIcon("C:\\Users\\r.pablo\\Desktop\\Will and Raden FInal Project For Computer Science 30S\\Pictures\\dice6.png")); // NOI18N
        getContentPane().add(lblDice6);
        lblDice6.setBounds(320, 450, 130, 140);

        lblDice7.setIcon(new javax.swing.ImageIcon("C:\\Users\\r.pablo\\Desktop\\Will and Raden FInal Project For Computer Science 30S\\Pictures\\dice1.png")); // NOI18N
        getContentPane().add(lblDice7);
        lblDice7.setBounds(230, 150, 110, 130);

        lblDice8.setIcon(new javax.swing.ImageIcon("C:\\Users\\r.pablo\\Desktop\\Will and Raden FInal Project For Computer Science 30S\\Pictures\\dice2.png")); // NOI18N
        getContentPane().add(lblDice8);
        lblDice8.setBounds(250, 250, 110, 140);

        lblDice9.setIcon(new javax.swing.ImageIcon("C:\\Users\\r.pablo\\Desktop\\Will and Raden FInal Project For Computer Science 30S\\Pictures\\dice3.png")); // NOI18N
        lblDice9.setText("jLabel1");
        getContentPane().add(lblDice9);
        lblDice9.setBounds(260, 360, 120, 150);

        lblDice10.setIcon(new javax.swing.ImageIcon("C:\\Users\\r.pablo\\Desktop\\Will and Raden FInal Project For Computer Science 30S\\Pictures\\dice4.png")); // NOI18N
        lblDice10.setText("jLabel1");
        getContentPane().add(lblDice10);
        lblDice10.setBounds(270, 440, 120, 130);

        lblDice11.setIcon(new javax.swing.ImageIcon("C:\\Users\\r.pablo\\Desktop\\Will and Raden FInal Project For Computer Science 30S\\Pictures\\dice5.png")); // NOI18N
        lblDice11.setText("jLabel1");
        getContentPane().add(lblDice11);
        lblDice11.setBounds(280, 500, 120, 180);

        lblDice12.setIcon(new javax.swing.ImageIcon("C:\\Users\\r.pablo\\Desktop\\Will and Raden FInal Project For Computer Science 30S\\Pictures\\dice6.png")); // NOI18N
        getContentPane().add(lblDice12);
        lblDice12.setBounds(580, 460, 120, 120);

        lblPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/s-l300.jpg"))); // NOI18N
        lblPicture.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblPicture);
        lblPicture.setBounds(0, 10, 1024, 1020);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/Money1.png"))); // NOI18N
        lblBackground.setText("sa");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(-30, 0, 1790, 1060);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Thanks for playing", "Monpoly", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);

    }//GEN-LAST:event_btnExitActionPerformed


    private void btnEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndActionPerformed
        for (JLabel die : dice) {
            die.setVisible(false);
        }
        btnEnd.setText("End turn"); // set the text
        btnHouse.setEnabled(true); // set the button to be enable so it
        // can be used 
        btnSell.setEnabled(true); // set the button to be  enable so it
        // can be used
        turn++; // add the turn count
        updateLabels();
        players[turn].takeTurn();
        updateLabels();
        System.out.println(turn);
        if (turn == players.length - 1) {
            turn = -1;
        }
        System.out.println("turn end");
        
    }//GEN-LAST:event_btnEndActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnd;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHouse;
    private javax.swing.JButton btnSell;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblDeeds;
    private javax.swing.JLabel lblDice1;
    private javax.swing.JLabel lblDice10;
    private javax.swing.JLabel lblDice11;
    private javax.swing.JLabel lblDice12;
    private javax.swing.JLabel lblDice2;
    private javax.swing.JLabel lblDice3;
    private javax.swing.JLabel lblDice4;
    private javax.swing.JLabel lblDice5;
    private javax.swing.JLabel lblDice6;
    private javax.swing.JLabel lblDice7;
    private javax.swing.JLabel lblDice8;
    private javax.swing.JLabel lblDice9;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblP1;
    private javax.swing.JLabel lblP2;
    private javax.swing.JLabel lblP3;
    private javax.swing.JLabel lblP4;
    private javax.swing.JLabel lblP5;
    private javax.swing.JLabel lblP6;
    private javax.swing.JLabel lblP7;
    private javax.swing.JLabel lblP8;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblTurn;
    // End of variables declaration//GEN-END:variables

    /**
     * it updates the money
     */
    private void updateLabels() {

        // shows how munch money the player has
        lblMessage.setText("$" + Integer.toString(players[turn].cash));
        // shows the name of the player and who turn it is
        lblTurn.setText(players[turn].name + "'s turn");

    }
    
}
